artifacts:
  files:
  - README.md
  - package.json
  - server.js
  - app.js
  - .env
  - buildspec.yml
  - appspec.yml
  - scripts/*
  - apis/**/*
  - auth/**
  - db/*
  - bin/*
  - public/**/*
  - scripts/*
  - tests/*
  - uploads/*
  - node_modules/**/*
  type: zip
eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::450524724960:role/aws-elasticbeanstalk-ec2-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
  Timeout: 10
phases:
  install:
    commands:
    - npm install
    - pip install --upgrade awscli
  post_build:
    commands:
    - rm -r node_modules
    - npm install --production
  pre_build:
    commands:
    - mv target/stella-api.war stella-api.war
version: 0.2
